### ISSUE TITLE
model.graph() path

### ISSUE THREAD

**Issue by caimeng2** [IMMM-SFA/naturf#168]
For your examples provided in `quickstarter.ipynb`, `model.execute()` works fine, but `model.graph()` doesn't. I encountered 

> ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH

It would be great if you could add some instructions on how to set up this path.

reference: https://github.com/openjournals/joss-reviews/issues/6712

**Comment by erexer** [comment]
Hi! A couple questions:
1. Did you `pip install graphviz`?
2. Did you install the requirements as listed in the pyproject.toml?
3. What operating system are you on?

**Comment by caimeng2** [comment]
1. Yes.
2. You mean installing the dependencies manually? No. I did pip install as the instruction says.  If you think this is the reason for the error, I would suggest handling the requirements automatically (e.g., `requirements.txt`)
3. macOS 13.0.1

**Comment by erexer** [comment]
makes sense, I'll add it to the required packages list
